name: GonnaCreep
version: 1.0
description: Randomly spawn creepers near players
author: davr
website: www.github.com/davr/GonnaCreep
main: org.davr.gonnacreep.GonnaCreep
commands:
  gonnacreep:
    description: Modify GonnaCreep settings
    usage: |
           /<command> [subcommand] [type]
           Example: /<command> setchance 1000 - Sets chance of creeper(lower=more)
           Example: /<command> chance - show current chance
